name: Test Hugo site

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.1
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check Hugo version
        run: hugo version
      
      - name: Validate Hugo configuration
        run: hugo check
      
      - name: Build site for testing
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "https://vietwillnguyen.github.io/vietwillnguyen.github.io/"
      
      - name: Check for build errors
        run: |
          if [ ! -d "public" ]; then
            echo "❌ Build failed: public directory not created"
            exit 1
          fi
          echo "✅ Build successful"
      
      - name: Validate HTML (basic check)
        run: |
          if command -v tidy &> /dev/null; then
            find public -name "*.html" -exec tidy -q -e {} \; || echo "⚠️ HTML validation warnings (non-critical)"
          else
            echo "ℹ️ HTML tidy not available, skipping HTML validation"
          fi
      
      - name: Check for broken links (basic)
        run: |
          echo "Checking for common broken link patterns..."
          if grep -r "404" public/ || grep -r "error" public/; then
            echo "⚠️ Potential broken links found (manual review recommended)"
          else
            echo "✅ No obvious broken links detected"
          fi